//! `integral-codegen` — pure-Rust build-time generation.
//!
//! Invoked from `build.rs` scripts to emit specialized per-angular-momentum
//! kernels and coefficient tables (e.g. Boys Chebyshev tables) as plain Rust
//! source — keeping all build-time code generation in one language rather than a
//! separate external generator toolchain.
//!
//! This crate currently exposes a minimal placeholder API.

#![forbid(unsafe_code)]

/// Placeholder generator entry point.
#[must_use]
pub fn generated_header() -> String {
    "// generated by integral-codegen\n".to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn header_is_nonempty() {
        assert!(generated_header().starts_with("// generated"));
    }
}
